Add language files and NEWSLETTER_EXPLAIN
phpbb-de/phpbb-ext-newsletter pull request #3
Opened 2017-08-22 19:11 UTC by Crizz0

For en/de

2017-08-29 18:18 UTC, Elsensee requested changes
Deutsch (Sie) noch? Sonst gut!

2017-08-29 18:18 UTC, Elsensee commented on language/de/common.php
> +	'NEWSLETTER_EXPLAIN'	=> 'Bei „Ja“ wird dir der regelmäßigen Newsletter per E-Mail zu gesendet.',
Abgesehen vom Typo würde ich das anders formulieren:
> Mit „Ja“ wird dir regelmäßig der Newsletter zugesendet.

Oder so.

2017-08-29 18:18 UTC, Elsensee commented on language/en/common.php
> +	'NEWSLETTER_EXPLAIN'	=> 'You will receive the frequent newsletter when this is activated.',
Würde ich ändern zu:
> When this is activated you will receive the newsletter frequently.

2017-11-15 18:41 UTC, Crizz0 commented on language/en/common.php
> +	'SEND_NEWSLETTER'		=> 'Sent newsletter',
Send = wie Gegenwart

2017-11-16 19:16 UTC, Crizz0 commented
@Elsensee all fine now?

2017-11-25 13:59 UTC, merged